-- 增加字段
ALTER TABLE WROX_USER
	ADD PERMISSION INTEGER UNSIGNED NOT NULL DEFAULT 0
AFTER 
	IS_ACTIVE;

-- 创建论坛表
CREATE TABLE WROX_FORUM(
	FORUM_ID	INTEGER 	UNSIGNED	NOT NULL	AUTO_INCREMENT,
	FORUM_NAME	VARCHAR(50)				NOT NULL,
	DESCRIPTION	VARCHAR(100)			NOT NULL,

	PRIMARY KEY(FORUM_ID)
)
ENGINE = MyISAM DEFAULT CHARACTER SET  UTF8 AUTO_INCREMENT = 0;


-- 创建消息表
CREATE TABLE WROX_FORUM_MESSAGE(
	MESSAGE_ID		BIGINT		UNSIGNED 	NOT NULL AUTO_INCREMENT,
	PARENT_MESSAGE_ID	BIGINT	UNSIGNED 	NOT NULL DEFAULT 0,
	FORUM_ID		INTEGER 	UNSIGNED	NOT NULL,
	USER_ID			INTEGER		UNSIGNED 	NOT NULL,
	SUBJECT			VARCHAR(100)			NOT NULL,
	MESSAGE_TEXT	TEXT 					NOT NULL,
	MESSAGE_DATE	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(MESSAGE_ID),

	FOREIGN KEY(PARENT_MESSAGE_ID)
		REFERENCES WROX_FORUM_MESSAGE(MESSAGE_ID),

	FOREIGN KEY(USER_ID)
		REFERENCES WROX_USER(USER_ID)
)
ENGINE= MyISAM DEFAULT CHARACTER SET UTF8 AUTO_INCREMENT=0;